# Generated by Django 4.2.18 on 2026-07-25 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('post', 'Post'), ('ad', 'Ad')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI job',
                'verbose_name_plural': 'AI jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='content_ai__status_a8a944_idx'), models.Index(fields=['job_type', '-created_at'], name='content_ai__job_typ_babaa9_idx')],
            },
        ),
    ]
