# Generated by Django 4.2.18 on 2026-07-25 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('prompt_task', models.CharField(db_index=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, db_index=True, max_length=50)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=100)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('language', models.CharField(blank=True, db_index=True, max_length=32)),
                ('rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('needs_improvement', 'Needs Improvement'), ('rejected', 'Rejected')], db_index=True, max_length=32)),
                ('reasons', models.JSONField(blank=True, default=list, help_text='List of reason codes (extendable).')),
                ('comment', models.TextField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('regenerated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_ai_generation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI generation feedback',
                'verbose_name_plural': 'AI generation feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating', '-created_at'], name='content_ai__rating_4f6373_idx'), models.Index(fields=['prompt_version', '-created_at'], name='content_ai__prompt__ff8a63_idx'), models.Index(fields=['provider', 'model_name', '-created_at'], name='content_ai__provide_b1f729_idx')],
            },
        ),
    ]
