"""
Django settings for codestar project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from django.contrib.messages import constants as messages
import dj_database_url

if os.path.isfile('env.py'):
    import env  # noqa: F401

# Load environment variables from .env at project root (BASE_DIR)
# This happens before reading any env-dependent settings
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Read DEBUG from environment; default to False for safety
DEBUG = os.environ.get("DEBUG", "False").lower() in {"1", "true", "yes", "on"}

# SECURITY WARNING: keep the secret key used in production secret!
# Use env SECRET_KEY; fall back to a local-only default when DEBUG is True
SECRET_KEY = os.environ.get("SECRET_KEY")
# Provide a dev fallback only if DEBUG is enabled
if SECRET_KEY is None and DEBUG:
    SECRET_KEY = "dev-secret-key-not-for-production"

# Fail fast if critical settings are missing in production
if not DEBUG and not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY must be set in environment when DEBUG is False."
    )

_default_allowed_hosts = (
    '8000-behzad17-djangoblog-0n6g7bsl8tl.ws.codeinstitute-ide.net,'
    '127.0.0.1,localhost,.herokuapp.com'
)
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS", _default_allowed_hosts
).split(",")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'csp',  # Content Security Policy
    'captcha',
    'cloudinary_storage',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_summernote',
    'cloudinary',
    'blog',
    'about',
    'askme',
    'ads',
]

SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',  # Content Security Policy - must be early
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'codestar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codestar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
# }

_default_sqlite_url = f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}"
_database_url = os.environ.get("DATABASE_URL", _default_sqlite_url)
DATABASES = {
    'default': dj_database_url.parse(
        _database_url,
        conn_max_age=600,
        ssl_require=not DEBUG
    )
}

if not DEBUG and os.environ.get("DATABASE_URL") is None:
    raise ImproperlyConfigured(
        "DATABASE_URL must be set in environment when DEBUG is False."
    )

if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }

CSRF_TRUSTED_ORIGINS = [
    "https://*.codeinstitute-ide.net/",
    "https://*.herokuapp.com"
]
_extra_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS += [o for o in _extra_csrf.split(",") if o]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]

# sso activation
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Email verification settings
# In development (DEBUG=True): Use 'optional' to allow login without email verification
# In production (DEBUG=False): Use 'mandatory' to require email verification
if DEBUG:
    ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Allow login without email verification in development
    ACCOUNT_EMAIL_REQUIRED = False  # Don't require email in development for easier testing
    # Use console backend for development (emails printed to console)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Require email verification in production
    ACCOUNT_EMAIL_REQUIRED = True  # Require email in production
    # Production email backend should be configured via environment variables
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')

SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Google emails are already verified, but we still require site verification
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create account on social login
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from social providers
ACCOUNT_FORMS = {
    "signup": "accounts.forms.CaptchaSignupForm",
}

# Google SSO settings in django-allauth
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID"),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET"),
            "key": "",
        }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MESSAGE_TAGS = {
    messages.ERROR: 'alert-danger',
    messages.SUCCESS: 'alert-success',
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Use CompressedStaticFilesStorage instead of Manifest version to avoid build errors
# Manifest can fail if there are any missing references in CSS/JS
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (for local development, Cloudinary is used in production)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security Headers (applied in all environments)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Permissions Policy (disable unused browser features)
PERMISSIONS_POLICY = {
    'camera': [],
    'microphone': [],
    'geolocation': [],
    'interest-cohort': [],  # FLoC
}

# Content Security Policy (CSP)
# Configured to allow necessary CDNs and Google OAuth while maintaining security
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",  # Required for Bootstrap inline scripts and some Django templates
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",
    "https://accounts.google.com",  # Google OAuth
    "https://apis.google.com",  # Google APIs
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",  # Required for Bootstrap inline styles
    "https://fonts.googleapis.com",
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",
)
CSP_FONT_SRC = (
    "'self'",
    "https://fonts.gstatic.com",
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",  # Font Awesome fonts
    "https://raw.githubusercontent.com",  # Vazir font may load from GitHub raw
    "data:",  # For inline font data
    "blob:",  # For blob URLs (some browsers use this for fonts)
)
CSP_IMG_SRC = (
    "'self'",
    "res.cloudinary.com",  # Cloudinary images
    "data:",  # Data URLs for images
    "https:",  # Allow HTTPS images from any source (needed for user content)
)
CSP_CONNECT_SRC = (
    "'self'",
    "https://accounts.google.com",  # Google OAuth
    "https://oauth2.googleapis.com",  # Google OAuth
    "https://www.googleapis.com",  # Google APIs
    "https://cdn.jsdelivr.net",  # Source maps and other requests
)
CSP_FRAME_SRC = (
    "'self'",
    "https://accounts.google.com",  # Google OAuth iframe
    "https://www.google.com",  # Google OAuth
)
CSP_FRAME_ANCESTORS = ("'none'",)  # Prevent clickjacking (complements X-Frame-Options)
CSP_BASE_URI = ("'self'",)
CSP_OBJECT_SRC = ("'none'",)  # Disable plugins
CSP_FORM_ACTION = ("'self'", "https://accounts.google.com")  # Allow Google OAuth form submissions

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
