# Generated by Django 4.2.18 on 2025-12-15 11:55

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advertisement Category',
                'verbose_name_plural': 'Advertisement Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', cloudinary.models.CloudinaryField(help_text='Upload the main ad image (will be displayed at 250x500).', max_length=255, verbose_name='ad_image')),
                ('target_url', models.URLField(help_text='External URL to open when the ad is clicked.', max_length=500)),
                ('url_approved', models.BooleanField(default=False, help_text='Whether the target URL has been reviewed and approved by an admin.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this ad without deleting it.')),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved ads will be visible on the site.')),
                ('start_date', models.DateField(blank=True, help_text='Optional start date for showing this ad.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for showing this ad.', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='ads.adcategory')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
