# Generated by Django 4.2.18 on 2025-12-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(blank=True, help_text='City where the service/business is located (optional).', max_length=100),
        ),
    ]
