# Generated by Django 4.2.18 on 2026-01-05 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0006_ad_featured_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Comment text content')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this comment was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='When this comment was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag (hide comment without deleting)')),
                ('ad', models.ForeignKey(help_text='The advertisement this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ads.ad')),
                ('author', models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='ad_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Comment',
                'verbose_name_plural': 'Ad Comments',
                'ordering': ['created_on'],
                'indexes': [models.Index(fields=['ad', 'created_on'], name='ads_adcomme_ad_id_26b5d3_idx'), models.Index(fields=['author', 'created_on'], name='ads_adcomme_author__65e204_idx')],
            },
        ),
    ]
