# Generated by Django 4.2.18 on 2026-01-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_adcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the service/business (optional).', max_length=500),
        ),
        migrations.AddField(
            model_name='ad',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL (optional).', max_length=500),
        ),
        migrations.AddField(
            model_name='ad',
            name='social_urls_approved',
            field=models.BooleanField(default=False, help_text='Whether social media URLs have been reviewed and approved by an admin. URLs are only clickable if approved.'),
        ),
        migrations.AddField(
            model_name='ad',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Telegram channel/group URL (optional).', max_length=500),
        ),
        migrations.AddField(
            model_name='ad',
            name='website_url',
            field=models.URLField(blank=True, help_text='Website URL (optional).', max_length=500),
        ),
    ]
