# Generated by Django 4.2.18 on 2026-01-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_address_ad_instagram_url_ad_social_urls_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(blank=True, help_text='Telephone number (optional).', max_length=50),
        ),
    ]
