# Generated by Django 4.2.18 on 2026-01-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_ad_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, help_text='Total number of views')),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text='When this ad was last viewed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the count was last updated')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view_count_cache', to='ads.ad')),
            ],
            options={
                'verbose_name': 'Ad View Count',
                'verbose_name_plural': 'Ad View Counts',
                'ordering': ['-total_views'],
            },
        ),
    ]
