# Generated by Django 4.2.18 on 2026-01-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_ad_plan_and_pro_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ad',
            new_name='ads_ad_city_865388_idx',
            old_name='ads_ad_city_idx',
        ),
        migrations.RenameIndex(
            model_name='ad',
            new_name='ads_ad_categor_6cfd35_idx',
            old_name='ads_ad_category_city_idx',
        ),
    ]
