# Generated by Django 4.2.18 on 2026-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_rename_ads_ad_city_idx_ads_ad_city_865388_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Advertisement Category', 'verbose_name_plural': 'Advertisement Categories'},
        ),
        migrations.AddField(
            model_name='adcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display Order'),
        ),
    ]
