# Generated by Django 4.2.18 on 2026-05-27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_adcategory_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcategory',
            name='image',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text='Optional image for the category slider. Falls back to default mapping if not set.',
                max_length=255,
                null=True,
                verbose_name='category_image',
            ),
        ),
    ]
