# Generated by Django 4.2.18 on 2026-07-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_migrate_extra_images_to_gallery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adgalleryimage',
            new_name='ads_adgalle_ad_id_dcfdf3_idx',
            old_name='ads_adgalle_ad_id_6f0a0d_idx',
        ),
    ]
