# Generated by Django 4.2.18 on 2026-01-04 01:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='نامک')),
                ('link_type', models.CharField(choices=[('podcast', '🎧 پادکست'), ('video', '🎬 فیلم / ویدئو'), ('radio', '📻 رادیو'), ('website', '🌐 وب\u200cسایت'), ('file', '📂 فایل آموزشی'), ('social', '📱 شبکه\u200cهای اجتماعی')], default='website', max_length=20, verbose_name='نوع لینک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='نام منبع')),
                ('url', models.URLField(verbose_name='لینک')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, help_text='تصویر کاور اختیاری', max_length=255, null=True, verbose_name='cover_image')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'لینک مرتبط',
                'verbose_name_plural': 'لینک\u200cهای مرتبط',
                'ordering': ['order', '-created_on'],
            },
        ),
    ]
