# Generated by Django 4.2.18 on 2026-07-05 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('related_links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120, verbose_name='نام انگلیسی')),
                ('name_fa', models.CharField(max_length=120, verbose_name='نام فارسی')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='نامک')),
                ('icon', models.CharField(help_text='نام کلاس Bootstrap Icons، مثال: bi-bank', max_length=64, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی لینک مفید',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای لینک مفید',
                'ordering': ['display_order', 'name_en'],
            },
        ),
        migrations.AddField(
            model_name='relatedlink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='links', to='related_links.usefullinkcategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
