# Generated by Django 4.2.18 on 2026-07-05 21:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_links', '0004_require_relatedlink_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedlink',
            options={'ordering': ['order', '-created_on'], 'verbose_name': 'لینک مفید', 'verbose_name_plural': 'لینک\u200cهای مفید'},
        ),
        migrations.AddField(
            model_name='relatedlink',
            name='short_description',
            field=models.CharField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر — فقط برای نمایش در فهرست لینک\u200cهای مفید.', max_length=160, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='relatedlink',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='تصویر اختیاری برای نمایش در فهرست منابع.', max_length=255, null=True, verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='relatedlink',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='relatedlink',
            name='link_type',
            field=models.CharField(choices=[('podcast', '🎧 پادکست'), ('video', '🎬 فیلم / ویدئو'), ('radio', '📻 رادیو'), ('website', '🌐 وب\u200cسایت'), ('file', '📂 فایل آموزشی'), ('social', '📱 شبکه\u200cهای اجتماعی')], default='website', max_length=20, verbose_name='نوع منبع'),
        ),
        migrations.AlterField(
            model_name='relatedlink',
            name='url',
            field=models.URLField(verbose_name='آدرس وب'),
        ),
    ]
