# Generated by Django 4.2.18 on 2026-07-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_links', '0008_remove_relatedlink_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedlink',
            name='short_description',
            field=models.CharField(blank=True, help_text='حداکثر ۱۸۰ کاراکتر — فقط برای نمایش در فهرست لینک\u200cهای مفید.', max_length=180, verbose_name='توضیح کوتاه'),
        ),
    ]
