# Generated by Django 4.2.18 on 2026-07-10 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Community Category',
                'verbose_name_plural': 'Community Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('hidden', 'Hidden')], default='open', max_length=20)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_discussions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussions', to='community.communitycategory')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_community_discussions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_deleted_community_discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('moderation_reason', models.CharField(blank=True, choices=[('new_user', 'New user (first 5 comments)'), ('contains_link', 'Contains link'), ('manual_review', 'Manual review')], max_length=50, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_replies', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.discussion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='communitycategory',
            index=models.Index(fields=['is_active', 'display_order'], name='community_c_is_acti_20bdde_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['discussion', 'approved', 'created_on'], name='community_r_discuss_58bd35_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['approved', '-created_on'], name='community_r_approve_f6dcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['author', 'approved'], name='community_r_author__f27089_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['moderation_reason', 'approved'], name='community_r_moderat_c19202_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['is_deleted', 'status', '-last_activity_at'], name='community_d_is_dele_d50baa_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['category', 'is_deleted', '-last_activity_at'], name='community_d_categor_2fbf61_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['author', '-created_on'], name='community_d_author__1555fc_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['is_deleted', '-created_on'], name='community_d_is_dele_bee4de_idx'),
        ),
        migrations.AddConstraint(
            model_name='discussion',
            constraint=models.CheckConstraint(check=models.Q(('reply_count__gte', 0)), name='community_discussion_reply_count_gte_0'),
        ),
    ]
