# Generated by Django 4.2.18 on 2025-12-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_likes_alter_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorite_posts',
        ),
    ]
