# Generated by Django 4.2.18 on 2025-12-10 23:13

from django.db import migrations


def assign_default_category(apps, schema_editor):
    """
    Assign a default category to posts that don't have one.
    Uses 'News & Politics' as the default category.
    """
    Post = apps.get_model('blog', 'Post')
    Category = apps.get_model('blog', 'Category')
    
    # Get or create a default category (News & Politics)
    default_category, created = Category.objects.get_or_create(
        slug='news-politics',
        defaults={'name': 'News & Politics'}
    )
    
    # Assign default category to posts without a category
    Post.objects.filter(category__isnull=True).update(category=default_category)


def reverse_assign_default_category(apps, schema_editor):
    """
    Reverse migration - set category to null for posts with default category.
    """
    Post = apps.get_model('blog', 'Post')
    Category = apps.get_model('blog', 'Category')
    
    try:
        default_category = Category.objects.get(slug='news-politics')
        Post.objects.filter(category=default_category).update(category=None)
    except Category.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_post_category'),
    ]

    operations = [
        migrations.RunPython(assign_default_category, reverse_assign_default_category),
    ]
