# Generated by Django 4.2.18 on 2025-12-10 23:30

from django.db import migrations, models
import django.db.models.deletion


def assign_default_category(apps, schema_editor):
    """
    Assign a default category to posts that don't have one.
    Uses 'News & Politics' as the default category.
    """
    Post = apps.get_model('blog', 'Post')
    Category = apps.get_model('blog', 'Category')
    
    # Get or create a default category (News & Politics)
    default_category, created = Category.objects.get_or_create(
        slug='news-politics',
        defaults={'name': 'News & Politics'}
    )
    
    # Assign default category to posts without a category
    Post.objects.filter(category__isnull=True).update(category=default_category)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_make_category_required'),
    ]

    operations = [
        # First, assign default category to any posts without one
        migrations.RunPython(assign_default_category, migrations.RunPython.noop),
        # Then, make the field required
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='posts',
                to='blog.category'
            ),
        ),
    ]

