# Generated by Django 4.2.18 on 2025-12-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_make_category_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional external URL for this post. Must be approved by admin to be displayed.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url_approved',
            field=models.BooleanField(default=False, help_text='Whether the external URL has been approved by admin to be displayed.'),
        ),
    ]
