# Generated by Django 4.2.18 on 2025-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Admins can pin a post to appear in the second slot of each row on the homepage.'),
        ),
    ]
