# Generated by Django 4.2.18 on 2025-12-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned_row',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Choose the target row (1-based) on the homepage where this post should appear in the second slot. Leave blank to auto-place.', null=True),
        ),
    ]
