# Generated by Django 4.2.18 on 2025-12-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_pinned_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_end_date',
            field=models.DateField(blank=True, help_text='End date for Events category posts only', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_start_date',
            field=models.DateField(blank=True, help_text='Start date for Events category posts only', null=True),
        ),
    ]
