# Generated by Django 4.2.18 on 2025-12-14 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_rename_and_remove_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_publish_without_approval', models.BooleanField(default=False, help_text="If True, user's posts will be published automatically without admin approval.")),
                ('expert_since', models.DateTimeField(blank=True, help_text='When expert access was granted', null=True)),
                ('user', models.OneToOneField(help_text='The user account associated with this profile', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-expert_since'],
            },
        ),
    ]
