# Generated by Django 4.2.18 on 2025-12-14 17:27

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """
    Create UserProfile for all existing users.
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('blog', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def reverse_create_profiles(apps, schema_editor):
    """
    Reverse migration - delete all profiles.
    """
    UserProfile = apps.get_model('blog', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_create_profiles),
    ]
