# Generated by Django 4.2.18 on 2025-12-16 21:40

from django.db import migrations


def translate_to_persian(apps, schema_editor):
    """
    Translate category names from English to Persian.
    
    IDEMPOTENT: Only updates categories if their current name is NOT already
    the target Persian value. Safe to run multiple times.
    """
    Category = apps.get_model('blog', 'Category')
    
    # Mapping: slug → Persian name
    # Slugs stay in English for URL safety
    translations = {
        'platform-updates': 'تازه‌های روز',
        'careers-economy': 'اقتصاد و بازار کار',
        'life-in-sweden': 'زندگی در سوئد',
        'law-integration': 'قانون و ادغام',
        'skills-learning': 'آموزش و مهارت',
        'events-announcements': 'رویدادها و اطلاعیه‌ها',
        'photo-gallery': 'گالری عکس',
        'public-services': 'خدمات عمومی',
        'stories-experiences': 'داستان‌ها و تجربه‌ها',
        'community-engagement': 'جامعه و مشارکت',
    }
    
    for slug, persian_name in translations.items():
        # Only update if category exists AND name is not already Persian
        # This makes the migration idempotent
        Category.objects.filter(
            slug=slug
        ).exclude(
            name=persian_name
        ).update(
            name=persian_name
        )


def reverse_to_english(apps, schema_editor):
    """
    Reverse translation: Persian → English.
    
    IDEMPOTENT: Only updates categories if their current name matches
    the Persian value. Safe rollback mechanism.
    """
    Category = apps.get_model('blog', 'Category')
    
    # Mapping: slug → (Persian name, English name)
    # We check Persian name to ensure we only rollback translated categories
    rollback_map = {
        'platform-updates': ('تازه‌های روز', 'Platform Updates'),
        'careers-economy': ('اقتصاد و بازار کار', 'Careers & Economy'),
        'life-in-sweden': ('زندگی در سوئد', 'Life in Sweden'),
        'law-integration': ('قانون و ادغام', 'Law & Integration'),
        'skills-learning': ('آموزش و مهارت', 'Skills & Learning'),
        'events-announcements': ('رویدادها و اطلاعیه‌ها', 'Events & Announcements'),
        'photo-gallery': ('گالری عکس', 'Photo Gallery'),
        'public-services': ('خدمات عمومی', 'Public Services'),
        'stories-experiences': ('داستان‌ها و تجربه‌ها', 'Stories & Experiences'),
        'community-engagement': ('جامعه و مشارکت', 'Community & Engagement'),
    }
    
    for slug, (persian_name, english_name) in rollback_map.items():
        # Only rollback if current name is Persian
        # This ensures idempotent rollback
        Category.objects.filter(
            slug=slug,
            name=persian_name
        ).update(
            name=english_name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_create_user_profiles'),
    ]

    operations = [
        migrations.RunPython(
            translate_to_persian,
            reverse_code=reverse_to_english
        ),
    ]

