# Generated by Django 4.2.18 on 2025-12-20 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_translate_categories_to_persian'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, help_text='Total number of views (excluding bots)')),
                ('unique_views', models.PositiveIntegerField(default=0, help_text='Approximate unique views (based on session/IP/UA combination)')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the count was last updated')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view_count_cache', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post View Count',
                'verbose_name_plural': 'Post View Counts',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(help_text='Full URL path for non-post pages', max_length=500)),
                ('session_key', models.CharField(db_index=True, help_text='Django session key for session-based deduplication', max_length=40)),
                ('ip_hash', models.CharField(db_index=True, help_text='SHA256 hash of IP address (anonymized for privacy)', max_length=64)),
                ('user_agent_hash', models.CharField(db_index=True, help_text='SHA256 hash of user agent (anonymized)', max_length=64)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referer', models.CharField(blank=True, help_text='HTTP Referer header', max_length=500)),
                ('is_bot', models.BooleanField(db_index=True, default=False, help_text='Whether this view is from a bot/crawler')),
                ('post', models.ForeignKey(blank=True, help_text='The post that was viewed (null for non-post pages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='blog.post')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', '-viewed_at'], name='blog_pagevi_post_id_352c99_idx'), models.Index(fields=['session_key', 'post'], name='blog_pagevi_session_9415ce_idx'), models.Index(fields=['ip_hash', 'user_agent_hash', 'post'], name='blog_pagevi_ip_hash_6b269d_idx')],
            },
        ),
    ]
