# Generated by Django 4.2.18 on 2025-12-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_postviewcount_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_site_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has completed site-level verification (terms acceptance, profile completion). Required for write actions.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site_verified_at',
            field=models.DateTimeField(blank=True, help_text='When site verification was completed', null=True),
        ),
    ]
