# Generated by Django 4.2.18 on 2025-12-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_backfill_site_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='welcome_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the welcome email has been sent to this user'),
        ),
    ]
