# Generated by Django 4.2.18 on 2025-01-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_userprofile_welcome_email_sent'),
    ]

    operations = [
        # Change approved default from True to False
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether this comment has been approved by admin'),
        ),
        # Add moderation_reason field
        migrations.AddField(
            model_name='comment',
            name='moderation_reason',
            field=models.CharField(blank=True, choices=[('new_user', 'New user (first 5 comments)'), ('contains_link', 'Contains link'), ('manual_review', 'Manual review')], help_text='Reason why comment requires moderation', max_length=50, null=True),
        ),
        # Add reviewed_by field
        migrations.AddField(
            model_name='comment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_comments', to=settings.AUTH_USER_MODEL),
        ),
        # Add reviewed_at field
        migrations.AddField(
            model_name='comment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When this comment was reviewed', null=True),
        ),
        # Add indexes for better query performance
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['approved', 'created_on'], name='blog_commen_approve_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'approved'], name='blog_commen_author_a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['moderation_reason', 'approved'], name='blog_commen_moderat_idx'),
        ),
    ]

