# Generated by Django 4.2.18 on 2025-01-27
# Data migration to set all existing comments to approved=True for backward compatibility

from django.db import migrations


def set_existing_comments_approved(apps, schema_editor):
    """Set all existing comments to approved=True to maintain backward compatibility."""
    Comment = apps.get_model('blog', 'Comment')
    # Update all existing comments to approved=True
    Comment.objects.all().update(approved=True)


def reverse_set_existing_comments_approved(apps, schema_editor):
    """Reverse migration - set all comments to approved=False."""
    Comment = apps.get_model('blog', 'Comment')
    # This is a one-way migration, but we provide reverse for completeness
    Comment.objects.all().update(approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_add_comment_moderation_fields'),
    ]

    operations = [
        migrations.RunPython(
            set_existing_comments_approved,
            reverse_set_existing_comments_approved
        ),
    ]

