# Generated by Django 4.2.18 on 2026-01-07 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0027_set_existing_comments_approved'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_approve_cd3272_idx',
            old_name='blog_commen_approve_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_author__293901_idx',
            old_name='blog_commen_author_a_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_moderat_a5120a_idx',
            old_name='blog_commen_moderat_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this post was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft-deleted this post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag. If True, post is hidden from public views.'),
        ),
    ]
