# Generated by Django 4.2.18 on 2026-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_rename_blog_commen_approve_idx_blog_commen_approve_cd3272_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postviewcount',
            options={'ordering': ['-total_views'], 'verbose_name': 'Post View Count', 'verbose_name_plural': 'Post View Counts'},
        ),
        migrations.RenameField(
            model_name='postviewcount',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='postviewcount',
            name='unique_views',
        ),
        migrations.AddField(
            model_name='postviewcount',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, help_text='When this post was last viewed', null=True),
        ),
        migrations.AlterField(
            model_name='postviewcount',
            name='total_views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of views'),
        ),
    ]
