# Generated by Django 4.2.18 on 2026-03-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_set_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_location',
            field=models.CharField(blank=True, help_text='Optional location for Events category posts (city, venue, or online).', max_length=200),
        ),
    ]
