# Generated by Django 4.2.18 on 2026-06-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_post_extra_image_1_post_extra_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
