# Generated by Django 4.2.18 on 2025-12-11 16:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_title', models.CharField(help_text="Expert title (e.g., 'Lawyer', 'Doctor', 'Accountant')", max_length=100)),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', help_text='Moderator profile image', max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True, help_text='Short bio about the moderator')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this moderator is currently active')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user account associated with this moderator', on_delete=django.db.models.deletion.CASCADE, related_name='moderator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Moderators',
                'ordering': ['expert_title', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question asked by the user (PRIVATE - visible only to user and moderator)')),
                ('answer_text', models.TextField(blank=True, help_text='The answer provided by the moderator (PRIVATE - visible only to user and moderator)')),
                ('answered', models.BooleanField(default=False, help_text='Whether the question has been answered')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('answered_on', models.DateTimeField(blank=True, help_text='When the question was answered', null=True)),
                ('moderator', models.ForeignKey(help_text='The moderator assigned to answer this question', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='askme.moderator')),
                ('user', models.ForeignKey(help_text='The user who asked the question', on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_on'],
            },
        ),
    ]
