# Generated by Django 4.2.18 on 2026-01-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_add_expert_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL (https:// or http://)', null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL (https:// or http://)', null=True, verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal or professional website URL (https:// or http://)', null=True, verbose_name='وب\u200cسایت'),
        ),
    ]
