"""AI Engine configuration package (architecture placeholder)."""

from content_ai.config.ai_engine import (
    DEFAULT_PROMPT_VERSION,
    DEFAULT_STYLE,
    ENABLE_EDITORIAL_WORKFLOW,
    ENABLE_KNOWLEDGE_ENGINE,
    ENABLE_KNOWLEDGE_INJECTION,
    ENABLE_RAG,
    FEATURE_FLAGS,
    FUTURE_AI_PROVIDERS,
    SUPPORTED_PROMPT_VERSIONS,
    SUPPORTED_STYLES,
    SYSTEM_MODULE_ORDER,
)

__all__ = [
    'DEFAULT_PROMPT_VERSION',
    'DEFAULT_STYLE',
    'ENABLE_EDITORIAL_WORKFLOW',
    'ENABLE_KNOWLEDGE_ENGINE',
    'ENABLE_KNOWLEDGE_INJECTION',
    'ENABLE_RAG',
    'FEATURE_FLAGS',
    'FUTURE_AI_PROVIDERS',
    'SUPPORTED_PROMPT_VERSIONS',
    'SUPPORTED_STYLES',
    'SYSTEM_MODULE_ORDER',
]
