# Generated by Django 4.2.18 on 2025-06-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_about_profile_image_remove_about_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
