# Generated by Django 4.2.18 on 2025-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(default="Welcome to our platform — a space created with purpose and heart.\nThis website is founded by a former journalist who now works in the field of integration, supporting immigrants in Sweden. The idea behind this platform is to build a dedicated space for Iranians living in Sweden — a place where voices can be heard, experiences can be shared, and a sense of community can grow.\n\nOur mission is to create a media hub where anyone, regardless of background or experience, can publish their personal stories, insights, and perspectives. Whether you're navigating life as a newcomer or sharing years of experience, your voice matters here.\n\nThis site aspires to become a central place for communication, connection, and support — a Stella of storytelling and solidarity among the Iranian community in Sweden.\n\nTogether, let's bring people closer."),
        ),
    ]
