# Generated by Django 4.2.18 on 2026-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='community_notifications',
            field=models.BooleanField(default=True, help_text='Receive in-app notifications for community replies.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('askme_specialist_answer', 'AskMe specialist answer'), ('ad_approved', 'Ad approved'), ('ad_rejected', 'Ad rejected'), ('ad_pro', 'Ad upgraded to Pro'), ('ad_expiring', 'Ad expiring soon'), ('ad_favorited', 'Ad favorited'), ('community_reply', 'Community reply'), ('weekly_digest', 'Weekly digest')], max_length=50),
        ),
    ]
